day.0=first
day.1=second
day.2=third
day.3=fourth
day.4=fifth
day.5=sixth
day.6=seventh
day.7=eighth
day.8=ninth
day.9=tenth
day.10=eleventh
day.11=twelfth

gift.0=a partridge in a pear tree
gift.1=two turtle doves
gift.2=three French Hens
gift.3=four Calling Birds
gift.4=five Golden Rings
gift.5=six Geese a Laying
gift.6=seven Swans a Swimming
gift.7=eight Maids a Milking
gift.8=nine Ladies Dancing
gift.9=ten Lords a Leaping
gift.10=eleven Pipers Piping
gift.11=twelve Drummers Drumming

firstLine=On the {0} day of Christmas my true love sent to me:

connector=and
